# platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
target 'betdice' do
pod 'AFNetworking'
pod 'MJExtension'
pod 'SocketRocket'


end



#post_install do |installer_representation|
#    installer_representation.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['ARCHS'] = 'armv7 arm64'
#            config.build_settings['ENABLE_BITCODE'] = 'NO'
#        end
#    end
#end


